### PR TITLE
Apply OpenSSL 1.1 patch using version detection of itself (not distribution)

### PR DESCRIPTION
**Pull request by robfrawley**
The `build.sh`'s selection control mechanism for adding `lt-open-ssl-1.1.patch` to `LT_BASE_PATCHES` is currently handled based on the *distribution release name*, but this strategy is flawed as the release name alone does not directly correlate to the `openssl` package version.

For example: I am running Ubuntu `17.10` (`artful`), which ships with `openssl@1.0.2g`. Based on the current detection strategy, the patch for `1.1` would not be applied. **But**, I utilize the extremely common [PHP PPA by Ondřej Surý](https://launchpad.net/~ondrej/+archive/ubuntu/php), which provides an updated `openssl@1.1.0g` package; the current implementation does not detect this as it performs no version checks against the actual package, causing the `rtorrent-ps` build to fail with compilation errors.

Instead, I propose we use the **detected openssl version**, instead of the distribution release name, to decide when the `lt-open-ssl-1.1.patch` patch should be applied. This PR does just that.

If you'd prefer the detection logic was handled in a different manner, please advise. I settled on a `case` control mechanism to make it easy to apply future patches based on the `openssl` version.

### CODE REVIEW

**Comment by chros73** [comment]
Are you sure that it still needs to be separated at all with 0.13.6?
This is the [updated version](https://github.com/chros73/rtorrent-ps-ch/blob/master/patches/vanilla_0.13.7_00-openssl_11_fix.patch) of the patch that I use with current master without any separation.

@robfrawley, you can test it with rtorrent-ps.

**Comment by robfrawley** [comment]
@chros73 Your patch doesn't apply cleanly for me, stopping the build:

```
lt-base-openssl-1.1-fix.patch
patching file configure.ac
Hunk #1 succeeded at 61 with fuzz 2 (offset -4 lines).
patching file Makefile.am
The next patch would create the file scripts/ssl.m4,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file src/utils/diffie_hellman.cc
Hunk #1 succeeded at 53 (offset -1 lines).
Hunk #2 succeeded at 85 (offset -1 lines).
patch unexpectedly ends in middle of line
Hunk #3 succeeded at 126 (offset -1 lines).
```

**Comment by chros73** [comment]
Hm, that's not a good news. So it requires more work with 0.13.6.
Either you can try to make it work or just forget what I said :)

**Comment by pyroscope** [comment]
Thanks, way better.
